--- Creates the roadmaps table for ai integration 
CREATE TABLE roadmaps (
  roadmap_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  description TEXT NOT NULL,
  duration_weeks INT NOT NULL,
  daily_hours INT NOT NULL,
  level TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);



-- Creates the 'goals' table to store high-level objectives
CREATE TABLE goals (
  goal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roadmap_id BIGINT REFERENCES roadmaps(roadmap_id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  metric TEXT NOT NULL, -- e.g., 'hours' or 'tasks'
  target_value NUMERIC NOT NULL,
  current_value NUMERIC NOT NULL DEFAULT 0,
  is_prioritized BOOLEAN DEFAULT false,
  deadline DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Creates the 'tasks' table for specific, actionable items linked to goals
CREATE TABLE tasks (
  task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  goal_id BIGINT REFERENCES goals(goal_id) ON DELETE SET NULL,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'todo', -- e.g., 'todo', 'in_progress', 'completed'
  is_prioritized BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Creates the 'time_entries' table to log manual work sessions
CREATE TABLE time_entries (
  time_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL REFERENCES tasks(task_id) ON DELETE CASCADE,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ,
  duration_minutes INT
);

-- Creates the 'rules' table for the automatic categorization engine
CREATE TABLE rules (
  rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL, -- e.g., 'productive', 'distracting'
  goal_id BIGINT REFERENCES goals(goal_id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Creates the 'activity_logs' table for the automatic tracking daemon
CREATE TABLE activity_logs (
  activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_name TEXT,
  window_title TEXT,
  category TEXT NOT NULL,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  duration_minutes INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);